name: Docker Updates Report

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger
  pull_request:
    types: [closed]

jobs:
  generate-report:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub

    - name: Generate Docker Updates Report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python scripts/docker_updates_tracker.py

    - name: Commit and push if changes exist
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add docs/docker-updates/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update Docker updates report" && git push)
