name: Python Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.0  # Check out the repository code

    - name: Set up Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3.10'  # Specify the Python version (e.g., 3.10)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip to the latest version
        pip install pytest  # Install pytest for testing

    - name: Create main.py
      run: |
        echo "def add(a, b):" > main.py
        echo "    return a + b" >> main.py

    - name: Create test_main.py
      run: |
        echo "from main import add" > test_main.py
        echo "" >> test_main.py
        echo "def test_add():" >> test_main.py
        echo "    assert add(2, 2) == 5, 'Test failed: 2 + 2 should equal 5'" >> test_main.py

    - name: Run Tests
      run: |
        echo "Running Tests"
        pytest test_main.py  # Run pytest on the test file