name: Python Hello World CI

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2  # Check out the repository code

    - name: Set up Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3.10'  # Specify the Python version (e.g., 3.10)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip to the latest version
        pip install pytest  # Install pytest for testing
        pip install requests  # Example of installing an additional package (requests)

    - name: Run Hello World Script
      run: |
        echo "Running Hello World Python Script"
        python -c "print('Hello, World!')"  # Simple Python command to print "Hello, World!"

    - name: Run Tests
      run: |
        echo "Running Tests"
        pytest  # Run pytest (you can add your own test files later)