name: Auto Approve and Merge Dependabot PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge-dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    env:
      GH_TOKEN: ${{ secrets.PAT_TOKEN }}  # Ensure this variable is available in all steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Authenticate GitHub CLI with PAT
        run: |
          echo "${GH_TOKEN}" | gh auth login --with-token
        # The GH_TOKEN environment variable is already set above.

      - name: Auto-approve the PR
        run: gh pr review "${{ github.event.pull_request.number }}" --approve

      - name: Auto-merge the PR
        run: gh pr merge "${{ github.event.pull_request.number }}" --squash -m "Auto merged Dependabot PR"