# .github/workflows/pr-slack-notify.yml

name: Slack PR Notification

# This workflow runs whenever a pull request is opened
on:
  pull_request:
    types: [opened]

jobs:
  slack_notification:
    name: Send Slack Notification
    runs-on: ubuntu-latest
    steps:
      # .github/workflows/pr-slack-notify.yml

      - name: Send PR Notification to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # Use a multi-line string ('>') to ensure the JSON is passed correctly.
          payload: >
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "🎉 *New Pull Request!* 🎉\n\n*Repository:*\n`${{ github.repository }}`\n*Author:*\n`${{ github.actor }}`"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*PR Title:*\n`${{ github.event.pull_request.title }}`"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Pull Request",
                        "emoji": true
                      },
                      "url": "${{ github.event.pull_request.html_url }}"
                    }
                  ]
                }
              ]
            }
        env:
          # Your Slack Webhook URL secret
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}